# Generated by Django 6.0 on 2026-01-13 15:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ficha', models.CharField(blank=True, help_text='Dejar en blanco para generar automático (ej: TS-2026-001). Si escribes uno manual, se respetará.', max_length=50, unique=True, verbose_name='ID Individual (Ficha)')),
                ('rol', models.CharField(blank=True, help_text='Ej: 1234-56', max_length=50, verbose_name='Rol de Avalúo')),
                ('nro_lote', models.CharField(blank=True, help_text='Ej: Lote A-4', max_length=50, verbose_name='Nro. Lote')),
                ('propietario', models.CharField(blank=True, help_text='Dato interno. No se muestra en la web.', max_length=255, verbose_name='Nombre Dueño (Privado)')),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha en que la propiedad ingresa al sistema. Editable.', verbose_name='Fecha de Ingreso')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVADO', 'Reservado'), ('VENDIDO', 'Vendido'), ('PAUSADO', 'Pausado / Suspendido')], default='DISPONIBLE', max_length=20)),
                ('tipo', models.CharField(choices=[('PARCELA', 'Parcela de Agrado'), ('URBANO', 'Sitio Urbano'), ('CASA', 'Casa'), ('AGRICOLA', 'Terreno Agrícola'), ('INDUSTRIAL', 'Terreno Industrial')], default='PARCELA', max_length=20)),
                ('titulo', models.CharField(max_length=200, verbose_name='Título Publicación')),
                ('slug', models.SlugField(blank=True, help_text='URL amigable. Se genera sola desde el título.', unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('referencia_locacion', models.CharField(blank=True, max_length=255, verbose_name='Referencia Pública')),
                ('comuna', models.CharField(default='Tomé', max_length=100)),
                ('sector', models.CharField(blank=True, help_text='Ej: Mirador, Rinco 2', max_length=100, verbose_name='Sector')),
                ('link_google_earth', models.URLField(blank=True, verbose_name='Link Google Earth/Maps')),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('operacion', models.CharField(choices=[('VENTA', 'Venta'), ('ARRIENDO', 'Arriendo')], default='VENTA', max_length=20)),
                ('moneda', models.CharField(choices=[('UF', 'UF'), ('CLP', 'Pesos Chilenos (CLP)')], default='CLP', help_text='Define si el precio fijo es en Pesos o UF.', max_length=5, verbose_name='Moneda Principal')),
                ('precio_lista', models.DecimalField(decimal_places=2, help_text='Ingresa el valor en la moneda seleccionada arriba. Este es el precio real.', max_digits=12, verbose_name='Precio de Lista')),
                ('precio_uf', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor UF (Calc)')),
                ('precio_pesos_referencia', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Valor Pesos (Calc)')),
                ('superficie_total_m2', models.PositiveIntegerField(verbose_name='Superficie Total (m²)')),
                ('superficie_construida_m2', models.PositiveIntegerField(blank=True, null=True, verbose_name='Sup. Construida (m²)')),
                ('topografia', models.CharField(choices=[('PLANO', 'Plano'), ('PENDIENTE_SUAVE', 'Pendiente Suave'), ('PENDIENTE_FUERTE', 'Pendiente Fuerte'), ('MIXTO', 'Mixto / Variado'), ('IRREGULAR', 'Irregular')], default='MIXTO', max_length=20)),
                ('topografia_detalle', models.TextField(blank=True, verbose_name='Detalle Topografía')),
                ('factibilidad_agua', models.CharField(choices=[('RED_PUBLICA', 'Red Pública (Essbio/Smapa)'), ('APR', 'APR (Agua Potable Rural)'), ('POZO', 'Pozo Profundo'), ('PUNTERA', 'Puntera'), ('VERTIENTE', 'Vertiente / Estero'), ('CAMION', 'Camión Aljibe'), ('NO_TIENE', 'No tiene / Sin factibilidad')], default='NO_TIENE', max_length=20, verbose_name='Agua')),
                ('factibilidad_luz', models.CharField(choices=[('MEDIDOR', 'Medidor Instalado'), ('FACTIBILIDAD', 'Factibilidad Técnica'), ('POSTACION', 'Postación Cerca'), ('SOLAR', 'Proyecto Solar Recomendado'), ('NO_TIENE', 'No tiene')], default='NO_TIENE', max_length=20, verbose_name='Luz')),
                ('factibilidad_alcantarillado', models.CharField(choices=[('INSTALADO', 'Instalado'), ('ACCESO_RED', 'Acceso a Red'), ('FOSA', 'Fosa Séptica'), ('NO_TIENE', 'No tiene')], default='NO_TIENE', max_length=20, verbose_name='Alcantarillado')),
                ('factibilidad_detalle', models.TextField(blank=True, verbose_name='Detalle Servicios')),
                ('dormitorios', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('banos', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('estacionamientos', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('publicada', models.BooleanField(default=False, help_text='Marcar para que aparezca en el sitio.', verbose_name='¿Publicada en Web?')),
                ('link_drive_fotos', models.URLField(blank=True, verbose_name='Link Drive (Privado)')),
                ('links_publicados', models.TextField(blank=True, help_text='Links de Yapo, PortalInmobiliario, etc.', verbose_name='Links Portales')),
                ('observaciones_internas', models.TextField(blank=True, verbose_name='Notas Internas (Privado)')),
                ('descripcion', models.TextField(verbose_name='Descripción Pública')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='ImagenPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='propiedades/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('es_principal', models.BooleanField(default=False)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='propiedades.propiedad')),
            ],
            options={
                'verbose_name': 'Imagen de Propiedad',
                'verbose_name_plural': 'Imágenes de Propiedades',
                'ordering': ['-es_principal', 'orden', 'subido_en'],
                'indexes': [models.Index(fields=['propiedad', 'es_principal'], name='propiedades_propied_df5a1e_idx'), models.Index(fields=['propiedad', 'orden'], name='propiedades_propied_88cf60_idx')],
            },
        ),
    ]
