# Generated by Django 6.0.1 on 2026-01-13 18:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ficha', models.CharField(blank=True, help_text='Dejar vacío para automático (TS-0001). Si escribes, se respeta.', max_length=20, unique=True, verbose_name='ID Ficha')),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Ingreso')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título Publicación')),
                ('slug', models.SlugField(blank=True, help_text='Se genera automático: ID + Título', max_length=255, unique=True)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVADO', 'Reservado'), ('VENDIDO', 'Vendido'), ('PAUSADO', 'Pausado / Suspendido')], default='DISPONIBLE', max_length=20)),
                ('tipo', models.CharField(choices=[('PARCELA', 'Parcela de Agrado'), ('URBANO', 'Sitio Urbano'), ('CASA', 'Casa'), ('AGRICOLA', 'Terreno Agrícola'), ('INDUSTRIAL', 'Terreno Industrial')], default='PARCELA', max_length=20)),
                ('rol', models.CharField(blank=True, max_length=50, verbose_name='Rol Avalúo')),
                ('nro_lote', models.CharField(blank=True, max_length=50, verbose_name='Nro. Lote')),
                ('propietario', models.CharField(blank=True, max_length=255, verbose_name='Dueño (Privado)')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('referencia_locacion', models.CharField(blank=True, max_length=255, verbose_name='Referencia')),
                ('comuna', models.CharField(default='Tomé', max_length=100)),
                ('sector', models.CharField(blank=True, max_length=100, verbose_name='Sector')),
                ('coordenadas_gps', models.CharField(blank=True, help_text='Ej: 36°30\'33.0"S 72°50\'48.0"W (Copiar tal cual de Google Earth)', max_length=100, verbose_name='Coordenadas GPS')),
                ('link_google_earth', models.URLField(blank=True, verbose_name='Link Mapa')),
                ('operacion', models.CharField(choices=[('VENTA', 'Venta'), ('ARRIENDO', 'Arriendo')], default='VENTA', max_length=20)),
                ('moneda', models.CharField(choices=[('UF', 'UF'), ('CLP', 'Pesos Chilenos (CLP)')], default='CLP', max_length=5, verbose_name='Moneda Principal')),
                ('precio_lista', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Lista')),
                ('precio_uf', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_pesos_referencia', models.PositiveBigIntegerField(blank=True, null=True)),
                ('superficie_total_m2', models.PositiveIntegerField(verbose_name='Sup. Total m²')),
                ('superficie_construida_m2', models.PositiveIntegerField(blank=True, null=True, verbose_name='Sup. Construida m²')),
                ('topografia', models.CharField(choices=[('PLANO', 'Plano'), ('PENDIENTE_SUAVE', 'Pendiente Suave'), ('PENDIENTE_FUERTE', 'Pendiente Fuerte'), ('MIXTO', 'Mixto'), ('IRREGULAR', 'Irregular')], default='MIXTO', max_length=20)),
                ('topografia_detalle', models.TextField(blank=True)),
                ('factibilidad_agua', models.CharField(choices=[('RED_PUBLICA', 'Red Pública'), ('APR', 'APR'), ('POZO', 'Pozo Profundo'), ('PUNTERA', 'Puntera'), ('VERTIENTE', 'Vertiente/Estero'), ('CAMION', 'Camión Aljibe'), ('NO_TIENE', 'No tiene')], default='NO_TIENE', max_length=20, verbose_name='Agua')),
                ('factibilidad_luz', models.CharField(choices=[('MEDIDOR', 'Medidor Instalado'), ('FACTIBILIDAD', 'Factibilidad Técnica'), ('POSTACION', 'Postación Cerca'), ('SOLAR', 'Proyecto Solar'), ('NO_TIENE', 'No tiene')], default='NO_TIENE', max_length=20, verbose_name='Luz')),
                ('factibilidad_alcantarillado', models.CharField(choices=[('INSTALADO', 'Instalado'), ('ACCESO_RED', 'Acceso a Red'), ('FOSA', 'Fosa Séptica'), ('NO_TIENE', 'No tiene')], default='NO_TIENE', max_length=20, verbose_name='Alcantarillado')),
                ('factibilidad_detalle', models.TextField(blank=True)),
                ('dormitorios', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('banos', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('estacionamientos', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('esta_publicada', models.BooleanField(default=False, help_text='Si no marcas esto, quiere decir que aún no se publica la propiedad en ningún portal.', verbose_name='¿Está publicada en algún sitio?')),
                ('plataformas_publicadas', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('FB_MARKET', 'Facebook Marketplace'), ('FB_PAGE', 'Página Facebook TerraStudio'), ('INSTAGRAM', 'Instagram'), ('PORTAL', 'PortalInmobiliario'), ('YAPO', 'Yapo.cl'), ('TOCTOC', 'TocToc'), ('WEB_PROPIA', 'Web TerraStudio.cl')], help_text='Marca las casillas para habilitar los campos de links correspondientes.', max_length=57, verbose_name='Plataformas Activas')),
                ('url_facebook', models.URLField(blank=True, verbose_name='Link Facebook Marketplace')),
                ('url_meta_ads', models.URLField(blank=True, verbose_name='Link Meta Enterprise (Ads)')),
                ('url_instagram', models.URLField(blank=True, verbose_name='Link Instagram')),
                ('url_portalinmobiliario', models.URLField(blank=True, verbose_name='Link PortalInmobiliario')),
                ('url_yapo', models.URLField(blank=True, verbose_name='Link Yapo.cl')),
                ('url_toctoc', models.URLField(blank=True, verbose_name='Link TocToc')),
                ('url_otra', models.URLField(blank=True, verbose_name='Link Otra Plataforma')),
                ('descripcion', models.TextField(verbose_name='Descripción Pública')),
                ('observaciones_internas', models.TextField(blank=True, verbose_name='Notas Internas')),
                ('link_drive_fotos', models.URLField(blank=True, help_text='Pega aquí el link a la carpeta de Google Drive donde guardas los originales de alta calidad.', verbose_name='Link Carpeta Drive (FOTOS ORIGINALES)')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='ImagenPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='propiedades/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('es_principal', models.BooleanField(default=False)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='propiedades.propiedad')),
            ],
            options={
                'ordering': ['-es_principal', 'orden', 'subido_en'],
            },
        ),
    ]
