# Generated by Django 6.0 on 2026-01-02 02:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del aviso')),
                ('slug', models.SlugField(blank=True, help_text='Identificador único para URL amigables. Se genera automáticamente desde el título si se deja en blanco.', unique=True)),
                ('precio_uf', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio en UF')),
                ('precio_pesos_referencia', models.PositiveBigIntegerField(help_text='Valor calculado para búsquedas y filtros. Requiere actualización periódica según valor UF vigente.', verbose_name='Precio en Pesos (Ref)')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVADO', 'Reservado'), ('VENDIDO', 'Vendido')], default='DISPONIBLE', help_text='Estado actual de la propiedad en el proceso de venta', max_length=20)),
                ('tipo', models.CharField(choices=[('PARCELA', 'Parcela de Agrado'), ('URBANO', 'Sitio Urbano'), ('CASA', 'Casa'), ('AGRICOLA', 'Terreno Agrícola'), ('INDUSTRIAL', 'Terreno Industrial')], default='PARCELA', help_text='Clasificación del tipo de propiedad', max_length=20)),
                ('dormitorios', models.PositiveSmallIntegerField(blank=True, help_text='Cantidad de dormitorios (aplicable solo a propiedades construidas)', null=True, verbose_name='Dormitorios')),
                ('banos', models.PositiveSmallIntegerField(blank=True, help_text='Cantidad de baños completos (aplicable solo a propiedades construidas)', null=True, verbose_name='Baños')),
                ('estacionamientos', models.PositiveSmallIntegerField(blank=True, help_text='Cantidad de estacionamientos disponibles', null=True)),
                ('superficie_total_m2', models.PositiveIntegerField(help_text='Área total del polígono del terreno en metros cuadrados', verbose_name='Superficie Terreno')),
                ('superficie_construida_m2', models.PositiveIntegerField(blank=True, help_text='Metros cuadrados de construcción edificada (aplicable solo a propiedades con edificación)', null=True, verbose_name='Sup. Construida')),
                ('rol', models.CharField(blank=True, help_text='Identificador fiscal del Servicio de Impuestos Internos (SII). Omitir en casos de cesión de derechos.', max_length=50, verbose_name='Rol de Avalúo')),
                ('topografia', models.CharField(choices=[('PLANO', '100% Plano'), ('LOMA_SUAVE', 'Lomaje Suave'), ('PENDIENTE', 'Pendiente Fuerte'), ('MIXTO', 'Mixto (Plano y Ladera)')], default='MIXTO', help_text='Característica predominante del relieve del terreno', max_length=20)),
                ('factibilidad_agua', models.CharField(choices=[('POTABLE', 'Agua Potable (Red Pública)'), ('APR', 'APR (Agua Potable Rural)'), ('PUNTERA', 'Puntera / Pozo'), ('CAMION', 'Camión Aljibe'), ('NO_TIENE', 'Sin factibilidad actual')], default='NO_TIENE', help_text='Tipo de abastecimiento de agua disponible o factible para la propiedad', max_length=20)),
                ('direccion', models.CharField(blank=True, help_text='Dirección física o referencia de ubicación', max_length=255)),
                ('comuna', models.CharField(default='Tomé', help_text='Comuna donde se ubica la propiedad', max_length=100)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, help_text='Coordenada de latitud en formato decimal. Ejemplo: -36.615517. Rango válido: -90 a 90', max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, help_text='Coordenada de longitud en formato decimal. Ejemplo: -72.952919. Rango válido: -180 a 180', max_digits=9, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
                'ordering': ['-creado'],
                'indexes': [models.Index(fields=['estado', 'tipo'], name='propiedades_estado_853f9f_idx'), models.Index(fields=['precio_pesos_referencia'], name='propiedades_precio__db503b_idx'), models.Index(fields=['comuna'], name='propiedades_comuna_68c182_idx')],
            },
        ),
        migrations.CreateModel(
            name='ImagenPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='propiedades/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message='Solo se permiten archivos en formato JPG, JPEG, PNG y WebP')], verbose_name='Imagen')),
                ('titulo', models.CharField(blank=True, help_text="Descripción breve de la fotografía. Ejemplo: 'Vista frontal', 'Cocina equipada', 'Vista panorámica'", max_length=200, verbose_name='Título de la imagen')),
                ('alt_text', models.CharField(blank=True, help_text='Descripción para accesibilidad web y optimización SEO. Se genera automáticamente si se omite.', max_length=255, verbose_name='Texto alternativo (SEO)')),
                ('es_principal', models.BooleanField(default=False, help_text='Designa esta imagen como la destacada. Solo puede existir una imagen principal por propiedad. Se utiliza en listados y portadas.', verbose_name='¿Es imagen principal?')),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Valor numérico para ordenamiento en galerías. Menor número aparece primero.', verbose_name='Orden de visualización')),
                ('subido_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('propiedad', models.ForeignKey(help_text='Propiedad a la que pertenece esta imagen', on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='propiedades.propiedad', verbose_name='Propiedad')),
            ],
            options={
                'verbose_name': 'Imagen de Propiedad',
                'verbose_name_plural': 'Imágenes de Propiedades',
                'ordering': ['orden', '-subido_en'],
                'indexes': [models.Index(fields=['propiedad', 'es_principal'], name='propiedades_propied_df5a1e_idx'), models.Index(fields=['propiedad', 'orden'], name='propiedades_propied_88cf60_idx')],
            },
        ),
    ]
