# Generated by Django 6.0 on 2026-01-02 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='precio_pesos_referencia',
            field=models.PositiveBigIntegerField(blank=True, help_text='Precio en pesos chilenos. Si se deja en blanco y se ingresa precio en UF, se calculará automáticamente.', null=True, verbose_name='Precio en Pesos (Ref)'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='precio_uf',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio en UF. Si se deja en blanco y se ingresa precio en pesos, se calculará automáticamente.', max_digits=10, null=True, verbose_name='Precio en UF'),
        ),
    ]
