# Generated by Django 6.0.1 on 2026-01-13 19:28

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='url_terrastudio',
            field=models.URLField(blank=True, null=True, verbose_name='Link Publicación Terrastudio'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='plataformas_publicadas',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('FB_MARKET', 'Facebook Marketplace'), ('FB_PAGE', 'Meta Enterprise'), ('INSTAGRAM', 'Instagram'), ('PORTAL', 'PortalInmobiliario'), ('YAPO', 'Yapo.cl'), ('TOCTOC', 'TocToc'), ('TERRA_WEB', 'TerraStudio.cl'), ('OTRA', 'Otra')], help_text='Marca las casillas para habilitar los campos de links correspondientes.', max_length=61, verbose_name='Plataformas Activas'),
        ),
    ]
